language: python

sudo: false

env:
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  # - luarocks make

install:
  - luarocks install busted
  - luarocks install luacheck

script:
  # - busted
  - luacheck SydneyHUD.lua lua/ script/
